Layout routs
qister/memstagram-typescript pull request #16
Opened 2021-02-11 14:57 UTC by Evgeny151

авторизация: тайтлы заменены на ant, кнопка заменена на ant, layout: верстка карточки, роуты

2021-02-12 09:03 UTC, qister requested changes

2021-02-12 09:03 UTC, qister commented on client/src/components/App/AppTemplate.tsx
> +      routes={routes}
Лучше не прокидывать роуты пропсами, а тогда сделать два роута - если авторизован и если не авторизован. И тут сразу рендерить в зависимости от того авторизован или нет.

2021-02-12 09:03 UTC, qister commented on client/src/components/Layout/Layout.tsx
> +          selectedKeys={onTapeDefault}
тут можно сразу заложить чтобы дефолтная выбранная ссылка бралась из адресной строки, а то получается если перейдешь сразу по ссылке /profile,  то выбранной все равно будет лента

2021-02-12 09:03 UTC, qister commented on client/src/customHooks/routes.tsx
> +        <Route path='/tape' exact>
вместо tape лучше feed) тейп эт кассета

2021-02-14 16:26 UTC, qister requested changes

2021-02-14 16:26 UTC, qister commented on client/src/components/App/AppTemplate.tsx
> +import { BrowserRouter as Router } from 'react-router-dom'
Импорты можно объединить в один

2021-02-14 16:26 UTC, qister commented on .vscode/settings.json
> +  "workbench.colorCustomizations": {
А зачем это? Просто тема для вскод?

2021-02-14 16:26 UTC, qister commented on client/src/components/App/AppTemplate.tsx
> +          ? <Route path='/' component={AppLayout}/>
лучше константу которая будет возвращать роуты в зависимости от авторизации и сразу ее сюда вставить типа 

```
  const routes = isAuthenticated ? (
    <>
      <Route path='/' component={AppLayout} /> <Redirect to='/' />
    </>
  ) : (
    <>
      <Route path='/login' component={Authorization} />
      <Redirect to='/login' />
    </>
  )
```

ток надо будет тогда поправить чтобы по дефолту feed был путь

2021-02-14 16:26 UTC, qister commented on client/src/components/App/AppTemplate.tsx
> +        {!isAuthenticated && <Redirect to='/login' /> }
Это тогда не нужно

2021-02-14 16:26 UTC, qister commented on client/src/components/AppLayout/AppLayoutBehavior.tsx
> +  const [defaultSelectedKey, setOnTapeDefault] = useState<string[]>(['/feed'])
можно сделать enum и туда вписать все пути сразу

2021-02-14 16:26 UTC, qister commented on client/src/customHooks/routes.tsx
> +export const useRoutes = () => {
Мы ток в одном месте теперь используем useRoutes, можно тогда вообще перенести функцию в AppLayoutTemplate, а этот файл удалить

2021-02-14 16:26 UTC, qister commented on client/src/pages/MemesTape/MemesTapeBehavior.tsx
> +import { MemesTapeTemplate } from './MemesTapeTemplate'
Поправь плиз тоже на MemesFeedTemplate

2021-02-14 17:21 UTC, Evgeny151 commented on .vscode/settings.json
> +  "workbench.colorCustomizations": {
я ваще хз че это ) само там чет добавилось, я Peacoc поставил расширение для вскода и поставил просто цвет для тёмного проекта один, он походу в проект именно вписался )

2021-02-15 07:51 UTC, qister commented on .vscode/settings.json
> +  "workbench.colorCustomizations": {
А можешь тогда плиз этот файл убрать из коммита

2021-02-15 12:50 UTC, merged