User profile
qister/memstagram-typescript pull request #29
Opened 2021-03-30 08:17 UTC by Evgeny151

страница профиля: добавление мемов в юзере на бэке, вывод аватарки, имейла, числа мемов, самих мемов на страницу профиля

2021-03-30 13:20 UTC, qister requested changes

2021-03-30 13:20 UTC, qister commented on client/src/pages/Profile/ProfileTemplate.tsx
> +    const serializeMemeUrl = (url: string) => {
Давай getMemeUrl, serialize по смыслу другое

2021-03-30 13:20 UTC, qister commented on client/src/redux/authToolkitRedux/StoreSlices/authorization.ts
> +  user: any
го в AuthorizationState будем хранить инфу об авторизации, а для юзера или отдельный стейт сделаем, либо будем о нем хранить инфу в appState

2021-03-30 13:20 UTC, qister commented on client/src/redux/authToolkitRedux/StoreSlices/authorization.ts
> +      state.user = action.payload.user
Это тогда не нужно, а надо будет проверить есть ли access токен в куки и если есть то по нему получить всю инфу о юзере(в др стейте уже)

2021-03-30 13:20 UTC, qister commented on server/src/routes/auth.routes.ts
> +      const userMemes = await Meme.find({ authorId: user._id })
тогда лучше отдельный роут типа /init_user сделать и там проверять токен и отдавать всю инфу по юзеру, ну и в нем формировать респонс типа {name: 'test', memes: userMemes} итд

2021-04-07 09:47 UTC, qister requested changes
Можешь еще сразу засквошить коммиты чтобы не было лишнего коммита о мерже

2021-04-07 09:47 UTC, qister commented on client/src/pages/Profile/ProfileTemplate.tsx
> +    // const { authorization: { user } } = useSelector((state: RootState) => state)
Можно тогда уже вынуть юзера из state.app

2021-04-07 09:47 UTC, qister commented on client/src/redux/authToolkitRedux/StoreSlices/authorization.ts
>    email: string
удали плиз email тоже

2021-04-07 09:47 UTC, qister commented on server/src/routes/auth.routes.ts
> +          user
это не нужно т.к. для получения юзера отдельный эндпоинт

2021-04-07 09:47 UTC, qister commented on server/src/routes/auth.routes.ts
>        const user = await User.findOne({ email })
тоже можно убрать

2021-04-07 12:47 UTC, qister commented on client/src/pages/Profile/ProfileTemplate.tsx
> +    // console.log('ProfileTemplate user', user);
убери плиз

2021-04-07 13:04 UTC, Evgeny151 commented on server/src/routes/auth.routes.ts
>        const user = await User.findOne({ email })
юзера ? он же нужен

2021-04-07 13:05 UTC, Evgeny151 commented on client/src/pages/Profile/ProfileTemplate.tsx
> +    // console.log('ProfileTemplate user', user);
так из app доставать или убирать в итоге ?

2021-04-07 13:10 UTC, qister requested changes

2021-04-07 13:10 UTC, qister commented on client/src/pages/Profile/ProfileTemplate.tsx
> +    // console.log('ProfileTemplate user', user);
консоль лог убрать, юзера доставать из app

2021-04-07 13:10 UTC, qister commented on server/src/routes/auth.routes.ts
>        const user = await User.findOne({ email })
точняк, я тупанул

2021-04-07 14:05 UTC, qister approved these changes

2021-04-07 14:05 UTC, merged

2021-04-07 14:06 UTC, qister commented
![](https://github.trello.services/images/mini-trello-icon.png) [профиль пользователя](https://trello.com/c/FT3aVg6M/11-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8C-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)